server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true

h2:
  console:
    enabled: true
    path: /h2-console  # Acesse o console H2 em http://localhost:8080/h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

location:
  maps:
    url: https://nominatim.openstreetmap.org